[package]
name = "automata"
version = "0.1.0"
authors = ["William Goodall <wgoodall01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.14.0"
